# Generated by Django 6.0 on 2026-01-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='booked_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration_days',
        ),
    ]
