# Generated by Django 6.0 on 2026-01-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_booking_date_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
